#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;

    CREATE DATABASE $POSTGRES_DB_Test;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_Test TO $POSTGRES_USER;
    

EOSQL

